# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ywmTvK-dSFIHGjHyqVUI-TvSOHEn3yMN
"""

areaLado = int(input("Digite a area de um lado do quadrado: "))

perimetro = areaLado * 4
areaTotal = areaLado * areaLado

print("perímetro:",perimetro," - área:",areaTotal,)